### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [pa-artem/Telegram-UI-Copy#1]
The goal is to check and improve skill of creating markup based on design or mockup.
This is looking quite far from original: 
![image](https://user-images.githubusercontent.com/5592397/90668585-fc881e80-e258-11ea-9acd-12d7c0efc990.png)

**Comment by pa-artem** [comment]
Thanks for the review. I've fixed the scrolls issue and tried to make my markup closer to the telegram desktop app original design.

![1](https://user-images.githubusercontent.com/67486583/90988461-8f97c000-e59b-11ea-8fdb-943902b6491c.png)
![2](https://user-images.githubusercontent.com/67486583/90988462-90c8ed00-e59b-11ea-853e-1b61dbb04b2e.png)

**Comment by IlyaMokin** [comment]
Looking is really cool! Thanks, the PR is accepted
